### ISSUE TITLE
Migrations Folder

### ISSUE THREAD

**Issue by spottedmahn** [bricelam/Sample-SplitMigrations#1]
I've followed your sample and when I create my migrations they go into a Migrations folder.  Not the end of the world but not desirable.  I tried the sample and it doesn't do that.

Do I need to change some config or did the tools change?

![image](https://cloud.githubusercontent.com/assets/14079228/24009266/d792a058-0a4a-11e7-9bc7-abc325759480.png)

**Comment by bricelam** [comment]
Just move them out of the folder. New migrations will be generated next the the previous one.

**Comment by bricelam** [comment]
You may also want to double-check their namespace. (And edit it accordingly.)

**Comment by spottedmahn** [comment]
thanks Brice!
