### ISSUE TITLE
Does not work for Entity Framework Core 2.0.1

### ISSUE THREAD

**Issue by pantonis** [bricelam/Sample-SplitMigrations#2]
This implementation does not work for Entity Framework Core 2.0.1 where you need a ContextFactory

**Comment by bricelam** [comment]
Can you clarify *does not work*?

**Comment by pantonis** [comment]
Sorry for the late reply. For some reason I didn't see that you replied.
Here is a my sample [project](https://drive.google.com/open?id=1qMFZGDsKuhPKj6Ph5mtMFI9q4IEZcakV) where when you call in VS 

```Add-Migration Migration -StartupProject "MigrationProblem.Console" -project "MigrationProblem.SqlServer"``` 

 I get

No DbContext was found in assembly 'MigrationProblem.SqlServer'. Ensure that you're using the correct assembly and that the type is neither abstract nor generic.

**Comment by pantonis** [comment]
Any news on this one?

**Comment by bricelam** [comment]
Does `-Verbose` provide any hints? I suspect this repo will work just fine after updating the packages.

**Comment by pantonis** [comment]
@bricelam The problem I have is in my [project](https://drive.google.com/file/d/1qMFZGDsKuhPKj6Ph5mtMFI9q4IEZcakV/view). Packages are uptodate.

Thanks

**Comment by xrkolovos** [comment]
it doesn't work in me too. Can you migrate it in .net core 2?

**Comment by WestDiscGolf** [comment]
Trying to get working and being unsuccessful. As a base clone with no other changes ...

![image](https://user-images.githubusercontent.com/374343/41183901-f2dacbd8-6b74-11e8-9245-5611b1567468.png)

And after upgrading everything to 2.1.0 and also implementing `IDesignTimeDbContextFactory<T>` in the following way ...
```C#
    public class MyDbContextFactory : IDesignTimeDbContextFactory<MyDbContext>
    {
        public MyDbContext CreateDbContext(string[] args)
        {
            var builder = new DbContextOptionsBuilder<MyDbContext>();
            IConfigurationRoot configuration = new ConfigurationBuilder()
                .SetBasePath(AppDomain.CurrentDomain.BaseDirectory)
                .AddJsonFile("appsettings.json")
                .Build();

            builder.UseSqlServer(configuration.GetConnectionString("Defa‌​ultConnection"));
            return new MyDbContext(builder.Options);
        }
    }
```
I now get ...
![image](https://user-images.githubusercontent.com/374343/41184331-7a4bda92-6b77-11e8-9082-7c650afe7154.png)
... and I have copied the appsettings.json into every project and marked them all as "copy if newer".

I've run out of ideas; it's late, time to give up for the night!

**Comment by WestDiscGolf** [comment]
I've rolled back to the start again and this time added a local `global.json` file to the root to make sure I was running 1.1.

In the package manager console I set the default project to "MyApp.Migrations", added a property to `MyEntity` and after building everything, ran `Add-Migration Migration2` and it appears to have created the migration files (not tried applying them yet).

Now it's time to try updating ...

Selected all "Updates" in the Solution level package manager and updated. There were issues with `netstandard1.4` needing to be updated, so I have, try again.

All nuget packages restored after being upgraded to 2.1 with all projects building successfully.

I deleted the test migration I ran earlier and ran the command again and got ...
```
Unable to create an object of type 'MyDbContext'. Add an implementation of 'IDesignTimeDbContextFactory<MyDbContext>' to the project, or see https://go.microsoft.com/fwlink/?linkid=851728 for additional patterns supported at design time.
```
Added in an implementation of IDesignTimeDbContextFactory and back to where I was re: connectionString issues.

*sigh*

I'm obviously missing something, if anyone has any pointers they would be much appreciated.

I have also tried the adding in the multiple TFMs and generate runtime config options which I found here - http://thedatafarm.com/data-access/the-secret-to-running-ef-core-2-0-migrations-from-a-net-core-or-net-standard-class-library/

**Comment by WestDiscGolf** [comment]
Thank you @bricelam  :-)

**Comment by bricelam** [comment]
Sorry it took me so long!

**Comment by WestDiscGolf** [comment]
No need to apologise. Appreciate the effort and help :-)

**Comment by WestDiscGolf** [comment]
Any tips on how to get it to run in VSTS in release management pipeline? ;-)

**Comment by WestDiscGolf** [comment]
For future reference this linked helped me - https://abelsquidhead.com/index.php/2017/07/31/deploying-dbs-in-your-cicd-pipeline-with-ef-core-code-first/
